version: '3.8'

services: 

  nginx:
    build:
      context: .
      dockerfile: docker/nginx.dockerfile
    ports: 
      - '8080:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    container_name: nginx
    depends_on: 
      - php
      - mysql

  # For removing permission denied for writing logs in Laravel app: 
  # Maybe not required, it works when added local user -> check php.dockerfile.   
  # sudo chmod -R o+w src/storage/ src/bootstrap/cache/
  php:
    build:
      context: .
      dockerfile: docker/php.dockerfile
    volumes:
      - ./src:/var/www/html
    container_name: php

  mysql:
    image: mysql:5.7
    env_file: 
      - ./env/mysql.env
    container_name: mysql
    volumes: 
      - data:/var/lib/mysql
    # restart: unless-stopped
    # tty: true

  composer:
    build: 
      context: ./docker
      dockerfile: composer.dockerfile
    # It has to be run from root with specified 'src' subfolder.
    # volumes:
    #  ./src:/var/www/html
    container_name: composer

  artisan:
    build: 
      context: .
      dockerfile: docker/php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    # depends_on: 
    #  - mysql
    container_name: artisan

  npm:
    image: node:14
    working_dir: /var/www/html
    entrypoint: ['npm']
    volumes: 
      - ./src:/var/www/html
    container_name: npm

  phpmyadmin:
    image: phpmyadmin
    ports:
      - '8081:80'
    env_file: 
      - ./env/phpmyadmin.env
    # restart: always
    depends_on: 
      - mysql
    container_name: phpmyadmin

volumes:
  data: